In [1]:
from nn.loss import MeanSquaredError
import numpy as np

In [2]:
a = MeanSquaredError()

In [3]:
a(1, 1)

0.0

In [4]:
from numbers import Number
from math import log

def categorical_crossentropy_loss(y_true, y_pred):
    """
    :param y_true: the current predicted output of the model
    :type y_true: np.ndarray
    :param y_pred: the expected output
    :type y_rped: np.ndarray
    :return: the categorical-crossentropy-loss
    :rtype: np.float64
    This function calculates and return the categorical-crossentropy-loss.
    "+1e-15" is just for adding a very small number to avoid np.log(0)
    """
    loss = -np.sum(y_true * (np.log(y_pred+1e-15)))
    return loss / (len(y_true))



In [5]:
y_true = np.array([[0, 1, 0], [0, 0, 1]])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
c = categorical_crossentropy_loss(y_true, y_pred)
c

1.1769391936907927

In [6]:
y_pred

array([[0.05, 0.95, 0.  ],
       [0.1 , 0.8 , 0.1 ]])

In [1]:
from datasets.mnist import MNIST

from nn.model import Sequential

from nn.activations import relu, tanh, sigmoid, softmax, leaky_relu
from nn.layers import Dense
from nn.loss import MeanSquaredError, CategoricalCrossEntropy
from nn.optimizer import GradientDescent
from nn.preprocessing import categorical_encoding, transform_input_data

import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [2]:
nn = Sequential(input_shape=(1, 784),
                layers=[
                    Dense(32, activation=leaky_relu),
                    Dense(10, activation='softmax')

                ],
                optimizer=GradientDescent(0.1),
                loss=CategoricalCrossEntropy())

nn.info()

+-------------------------------------------------+
|                model: Sequential                |
+-------+---------------+------------+------------+
| Layer | Weights shape | Bias shape | activation |
+-------+---------------+------------+------------+
| Dense |   (32, 784)   | <(32, 1)>  | leaky_relu |
| Dense |    (10, 32)   | <(10, 1)>  |  softmax   |
+-------+---------------+------------+------------+
Optimizer: GradientDescent
loss: categorical_cross_entropy


['Dense', '(32,784)', '<(32,', '1)>', 'leaky_relu']

In [41]:
from prettytable import PrettyTable
    
x = PrettyTable()
x.field_names = ["City name", "Area", "Population", "Annual Rainfall"]
x.add_row(['Moscow', 123123, 123123, 12312])
print(x)


+-----------+--------+------------+-----------------+
| City name |  Area  | Population | Annual Rainfall |
+-----------+--------+------------+-----------------+
|   Moscow  | 123123 |   123123   |      12312      |
+-----------+--------+------------+-----------------+


In [ ]:
i

In [1]:
import prettytable

ModuleNotFoundError: No module named 'prettytable'

In [2]:
data = MNIST(mode='full')

All required files are exist!


In [3]:

train_data, test_data = data.dataset
X_train, y_train = test_data
X_test, y_test = test_data

print('Train:', X_train.shape, y_train.shape)
print('Test:', X_test.shape, y_test.shape)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test_ = scaler.transform(X_test)

X_test_ = transform_input_data(X_test_)
X_train_ = transform_input_data(X_train)

y_train_ = categorical_encoding(y_train)
y_train_ = transform_input_data(y_train_)

print('Training shapes')
print('X_train:', X_train_.shape)
print('y_train:', y_train_.shape)

Train: (10000, 784) (10000,)
Test: (10000, 784) (10000,)
(10000,)
Training shapes
X_train: (10000, 784, 1)
y_train: (10000, 10, 1)


In [4]:
nn = Sequential(input_shape=(1, 784),
                layers=[
                    Dense(32, activation=leaky_relu),
                    Dense(10, activation='softmax')

                ],
                optimizer=GradientDescent(0.1),
                loss=CategoricalCrossEntropy())

nn.info()

model: Sequential
------------------------------
Dense | (32,784) <(32, 1)> | leaky_relu
Dense | (10,32) <(10, 1)> | softmax
Optimizer: GradientDescent
loss: categorical_cross_entropy


In [14]:
a= '(32,784) <(32, 1)> leaky_relu'
a.split()

['(32,784)', '<(32,', '1)>', 'leaky_relu']

In [3]:

a = repr(nn.weights.wl1)


['(10,32)', '<(10,', '1)>', 'softmax', 0]

In [9]:
nn.forward(X_train_[1])

array([[0.07590196],
       [0.09019457],
       [0.08169743],
       [0.09542794],
       [0.18013433],
       [0.11897169],
       [0.08444522],
       [0.07208916],
       [0.11108785],
       [0.09004985]])

In [10]:
n = np.random.choice(range(len(X_train_)))
print(n)
nn.fit([X_train_[n]], [y_train_[n]], epochs=2)



# sus = X_train_[n]
# nn.forward(sus)

5580
<class 'list'> and <class 'list'> types as input data
Start training for 2 epochs


Epoch 1: 100%|██████████| 1/1 [00:00<00:00, 500.75samples/s]


categorical_cross_entropy: 0.2428749593210595


Epoch 2: 100%|██████████| 1/1 [00:00<00:00, 500.04samples/s]

categorical_cross_entropy: 0.24908184467572342


In [12]:
nn.fit(X_train_, y_train_, epochs=2)

<class 'numpy.ndarray'> and <class 'numpy.ndarray'> types as input data
Start training for 2 epochs


Epoch 1: 100%|██████████| 10000/10000 [00:13<00:00, 730.51samples/s]


categorical_cross_entropy: 2.302585092994046


Epoch 2: 100%|██████████| 10000/10000 [00:11<00:00, 858.16samples/s]

categorical_cross_entropy: 2.302585092994046


In [13]:
nn.weights.wl0.weights

array([[2.81502602e-03, 9.94305691e-03, 9.89621879e-03, ...,
        2.88772962e-03, 3.14301970e-04, 3.02444976e-03],
       [3.22840797e-03, 8.63284976e-04, 6.54818592e-03, ...,
        5.33812051e-03, 2.38037526e-03, 8.17671149e-03],
       [1.20525487e-03, 1.86226016e-03, 1.80422846e-03, ...,
        5.34486227e-03, 5.24268917e-03, 7.11610660e-03],
       ...,
       [6.63143676e-03, 4.19025945e-03, 7.57930124e-03, ...,
        1.16471069e-03, 7.69609734e-03, 5.85264882e-04],
       [4.63019200e-03, 2.47159720e-05, 5.80103808e-03, ...,
        3.67659457e-03, 8.44637804e-03, 1.84509258e-04],
       [6.11765193e-03, 8.63943454e-03, 3.40758718e-03, ...,
        1.54614323e-03, 7.16398836e-03, 6.21395014e-03]])

In [81]:
y_ = nn.predict(X_train_[45])
y_

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [80]:
y_train_[45]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
a = X_train_[1]
a = np.zeros(3)
b = np.ones(3)

In [116]:
np.exp(0)/np.sum(np.exp([-2.3]))

9.97418245481472

In [117]:
np.exp(0)

1.0