In [1]:
from nn.loss import MeanSquaredError
import numpy as np

In [2]:
a = MeanSquaredError()

In [3]:
a(1, 1)

0.0

In [4]:
from datasets.mnist import MNIST

from nn.model import Sequential

from nn.activations import relu, tanh, sigmoid, softmax, leaky_relu
from nn.layers import Dense
from nn.loss import MeanSquaredError, CategoricalCrossEntropy
from nn.optimizer import GradientDescent
from nn.preprocessing import categorical_encoding, transform_input_data

import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("error")

In [5]:
data = MNIST(mode='full')

All required files are exist!


In [6]:

train_data, test_data = data.dataset
X_train, y_train = test_data
X_test, y_test = test_data

print('Train:', X_train.shape, y_train.shape)
print('Test:', X_test.shape, y_test.shape)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test_ = scaler.transform(X_test)

X_test_ = transform_input_data(X_test_)
X_train_ = transform_input_data(X_train)

y_train_ = categorical_encoding(y_train)
y_train_ = transform_input_data(y_train_)

print('Training shapes')
print('X_train:', X_train_.shape)
print('y_train:', y_train_.shape)

Train: (10000, 784) (10000,)
Test: (10000, 784) (10000,)
(10000,)
Training shapes
X_train: (10000, 784, 1)
y_train: (10000, 10, 1)


In [7]:
nn = Sequential(input_shape=(1, 784),
                layers=[
                    Dense(32, activation=leaky_relu, weights_strategy='xavier'),
                    Dense(10, activation=softmax, weights_strategy='xavier')

                ],
                optimizer=GradientDescent(0.1),
                loss=MeanSquaredError())

nn.info()

+-------------------------------------------------+
|                model: Sequential                |
+-------+---------------+------------+------------+
| Layer | Weights shape | Bias shape | activation |
+-------+---------------+------------+------------+
| Dense |   (32, 784)   | <(32, 1)>  | leaky_relu |
| Dense |    (10, 32)   | <(10, 1)>  |  softmax   |
+-------+---------------+------------+------------+
Optimizer: GradientDescent
loss: MeanSquaredError


In [8]:
nn.weights.wl0

(32, 784)|<(32, 1)>|leaky_relu

In [9]:
y_hat = nn.forward(X_train_[1])
l = MeanSquaredError()

In [10]:
vec = np.array([1, 2])
print(softmax(vec))
vec = np.array([10, 9999])
print(softmax(vec)) 

[0.26894142 0.73105858]
[0. 1.]


In [11]:
for wl in nn.weights.layers:
    print(wl.weights.mean())

0.08820530758817485
0.1603032720349443


In [12]:
nn.fit(X_train_, y_train_, epochs=2)

<class 'numpy.ndarray'> and <class 'numpy.ndarray'> types as input data
Start training for 2 epochs


Epoch 1:  47%|████▋     | 4743/10000 [00:04<00:04, 1166.67samples/s]


[[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]


UnboundLocalError: local variable 'shifted_array' referenced before assignment

In [30]:
for wl in nn.weights.layers:
    print(wl.weights.mean())

-0.18569194447838824


In [19]:
from math import isinf


def find_inf(array: np.ndarray):
    res = list()
    for order, arr in enumerate(array):
        if any(np.isinf(arr)):
            res.append(order)
            
    return res

find_inf(y_train_)

[]

In [18]:
any(np.isinf(X_train_[0]))

False

In [16]:
y_ = nn.predict(X_train_[45])
y_

array([0.13651324, 0.06796922, 0.07200875, 0.07525509, 0.12174875,
       0.10276425, 0.11668355, 0.12796563, 0.11536249, 0.06372902])

In [14]:
y_train_[45]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
a = X_train_[1]
a = np.zeros(3)
b = np.ones(3)

In [116]:
np.exp(0)/np.sum(np.exp([-2.3]))

9.97418245481472

In [117]:
np.exp(0)

1.0

In [9]:
sizes = [784, 32, 10]
w = [np.random.randn(y, x) / np.sqrt(x)
                            for x, y in zip(sizes[:-1], sizes[1:])]

In [11]:
w[0].shape

(32, 784)

In [13]:
nn.weights.wl0.weights.shape

(32, 784)

In [14]:
for x, y in zip(sizes[:-1], sizes[1:]):
    print(x, y)

784 32
32 10


In [17]:
a = (3, 2)
np.random.rand(*a)

array([[0.37549475, 0.80492171],
       [0.24848559, 0.37846976],
       [0.95026755, 0.41954555]])